# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function() {
    invisible(.Call(`_lda_svi_test`))
}

lda_online_cpp <- function(doc_ids, terms, counts, K, passes, batchsize) {
    .Call(`_lda_svi_lda_online_cpp`, doc_ids, terms, counts, K, passes, batchsize)
}

