# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lda_online_cpp <- function(doc_ids, terms, counts, K, passes, batchsize, maxiter, tau_0, kappa, eta, alpha) {
    .Call(`_lda_svi_lda_online_cpp`, doc_ids, terms, counts, K, passes, batchsize, maxiter, tau_0, kappa, eta, alpha)
}

